import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

=======
import NavBar from "@/Components/shared/NavBar";
import Banner from "@/Components/Homepage/banner";
import AnimalCard from "@/Components/ui/AnimalCard";
import FooterPage from "@/Components/Homepage/FooterPage";
>>>>>>> f020e672f800807dbd666dd195d2216ab1a026bf

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<<<<<<< HEAD
      <body className="min-h-full flex flex-col">{children}
        <ToastContainer 
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
=======
      <body className="min-h-full flex flex-col">
        {children}
>>>>>>> f020e672f800807dbd666dd195d2216ab1a026bf
      </body>
    </html>
  );
}
